package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, REQUEST_SUZUKI_TOKEN, SEND_SUZUKI_TOKEN, PUT_UNLOCK, DELETE, DELETE_UNLOCK, BACKUP, DELETE_BACKUP, SHUT_DOWN, GOODBYE, PING, PONG, RECOVERY, COMRADE_ASK, COMRADE_ANSWER, COMRADE_CONTACT, COMRADE_ALIVE
}
